/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Autoclean_Form;

/**
 *
 * @author Fadhil
 */


import AutoClean_Connection.Koneksi;
import javax.swing.ImageIcon;
import java.util.Random;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

 

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    public static String loggedInUsername;
    
    public Login() {
        initComponents();
        ImageIcon img = new ImageIcon("Autoclean-Assets/logo.png");
        setIconImage(img.getImage());
        setResizable(false);
        setLocationRelativeTo(null);
        generateCaptcha();
    }
    
    String generatedCaptcha = "";
    boolean isPasswordVisible = false;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LoginrUsername = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblCaptcha = new javax.swing.JLabel();
        txtCaptchaInput = new javax.swing.JTextField();
        btnRefreshCaptcha = new javax.swing.JButton();
        toRegister = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        LoginPassword = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 241, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(776, 520));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 260, 90, 21);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Pesan Janji Temu Mobil Pesan Janji Temu Mobil");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 70, 420, 25);

        jLabel4.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 36)); // NOI18N
        jLabel4.setText("Masuk AutoClean JavaDesk");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 40, 430, 40);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Username");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 190, 90, 24);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Masukan Captcha");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 310, 160, 21);
        jPanel1.add(LoginrUsername);
        LoginrUsername.setBounds(220, 190, 260, 30);

        buttonLogin.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.setBorder(null);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogin);
        buttonLogin.setBounds(60, 470, 170, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AutoClean-Assets/logo.png")));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 170, 200, 200);

        lblCaptcha.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblCaptcha.setText("kode captcha");
        jPanel1.add(lblCaptcha);
        lblCaptcha.setBounds(60, 350, 120, 24);

        txtCaptchaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaptchaInputActionPerformed(evt);
            }
        });
        jPanel1.add(txtCaptchaInput);
        txtCaptchaInput.setBounds(220, 340, 260, 50);

        btnRefreshCaptcha.setText("Muat Ulang Kode");
        btnRefreshCaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCaptchaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefreshCaptcha);
        btnRefreshCaptcha.setBounds(60, 430, 140, 23);

        toRegister.setBackground(new java.awt.Color(221, 241, 255));
        toRegister.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        toRegister.setForeground(new java.awt.Color(51, 51, 51));
        toRegister.setText("Belum punya akun, Daftar aja dulu!");
        toRegister.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        toRegister.setBorderPainted(false);
        toRegister.setContentAreaFilled(false);
        toRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toRegister.setFocusPainted(false);
        toRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(toRegister);
        toRegister.setBounds(530, 510, 210, 35);

        jCheckBox1.setText("Masuk Sebagai Admin");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(60, 510, 160, 20);
        jPanel1.add(LoginPassword);
        LoginPassword.setBounds(220, 252, 260, 30);

        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AutoClean-Assets/view.png"))); // NOI18N
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showPassword);
        showPassword.setBounds(490, 250, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
    String inputCaptcha = txtCaptchaInput.getText();
    
    if (!inputCaptcha.equals(generatedCaptcha)) {
        JOptionPane.showMessageDialog(this, "Captcha salah!");
        generateCaptcha(); // regenerate
        return;
    }

    String user = LoginrUsername.getText().trim();
    String pass = LoginPassword.getText().trim();
    String hashedPass = hashPassword(pass);
    
    boolean sebagaiAdmin = jCheckBox1.isSelected();
    
    String sql = "SELECT * FROM akun WHERE username = ? AND password = ?";
    try (Connection conn = Koneksi.connect();
         PreparedStatement ps = conn.prepareStatement(sql)) {

         ps.setString(1, user);
         ps.setString(2, hashedPass);
         try (ResultSet rs = ps.executeQuery()) {
             if (rs.next()) {
                 int id = rs.getInt("id");
                 String uname = rs.getString("username");
                 
                 
                 Login.loggedInUsername = uname;

                 if (sebagaiAdmin && id == 1) {
                     JOptionPane.showMessageDialog(this, "Login admin berhasil!");
                     // buka form admin
                     new AdminDashboard().setVisible(true);
                     
                     dispose();
                 } else if (!sebagaiAdmin) {
                     JOptionPane.showMessageDialog(this, "Login user berhasil!");
                     // buka form pelanggan
                     new Pelanggan().setVisible(true);
                     dispose();
                 } else {
                     JOptionPane.showMessageDialog(this, "Anda bukan admin!");
                 }
             } else {
                 JOptionPane.showMessageDialog(this, "Username atau password salah!");
                 generateCaptcha();
             }
         }
         
    
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error koneksi database:\n" + ex.getMessage());
        
     
    }    }//GEN-LAST:event_buttonLoginActionPerformed

    private void txtCaptchaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaptchaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaptchaInputActionPerformed

    private void btnRefreshCaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCaptchaActionPerformed
    generateCaptcha();
    }//GEN-LAST:event_btnRefreshCaptchaActionPerformed

    private void toRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRegisterActionPerformed
        new Register().setVisible(true);
        dispose();
    }//GEN-LAST:event_toRegisterActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed

       

        if (isPasswordVisible) {
            LoginPassword.setEchoChar('\u2022');
        } else {
            LoginPassword.setEchoChar((char)0); // show text
        }
        isPasswordVisible = !isPasswordVisible; // balik kondis
    }//GEN-LAST:event_showPasswordActionPerformed

    private void generateCaptcha() {
    String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    StringBuilder captcha = new StringBuilder();
    Random rand = new Random();
    for (int i = 0; i < 4; i++) {
        captcha.append(chars.charAt(rand.nextInt(chars.length())));
    }
    generatedCaptcha = captcha.toString();
    lblCaptcha.setText(generatedCaptcha); // Tampilkan captcha ke label
}

    private String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashBytes = md.digest(password.getBytes());
        
        StringBuilder sb = new StringBuilder();
        for (byte b : hashBytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
        
    } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException(e);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JTextField LoginrUsername;
    private javax.swing.JButton btnRefreshCaptcha;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCaptcha;
    private javax.swing.JButton showPassword;
    private javax.swing.JButton toRegister;
    private javax.swing.JTextField txtCaptchaInput;
    // End of variables declaration//GEN-END:variables
}
