/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Autoclean_Form;

/**
 * Kelas Pelanggan merepresentasikan antarmuka pengguna (GUI) untuk pelanggan 
 * yang ingin memesan layanan pencucian kendaraan melalui aplikasi AutoClean.
 * 
 * Fitur utama:
 * - Input data pelanggan dan kendaraan
 * - Pemilihan opsi pencucian
 * - Pemilihan jadwal pencucian
 * - Penyimpanan data ke database
 * - Navigasi ke halaman riwayat dan logout
 * 
 * Kelas ini menggunakan komponen Swing dan JCalendar.
 * 
 * @author Fadhil
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import AutoClean_Code.User;
import AutoClean_Code.PelangganModel;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.*;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;



public class Pelanggan extends javax.swing.JFrame {
    /**
     * Creates new form Pelanggan
     */
    
    /**
     * Konstruktor untuk kelas Pelanggan.
     * Inisialisasi komponen UI, mengatur posisi, dan memuat gambar.
     */
    public Pelanggan() {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null); // opsional: biar frame muncul di tengah layar
        
        ImageIcon logo = new ImageIcon("/AutoClean-Assets/logo.png");
        setIconImage(logo.getImage());
        
        
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/AutoClean-Assets/image.jpg"));
        Image img = icon.getImage();
        Image scaledImg = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(scaledImg));
        
        
        
        

    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        inputNomorTelp = new javax.swing.JTextField();
        inputMerkKendaraan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        inputOpsiPencucian = new javax.swing.JComboBox<>();
        inputPlat = new javax.swing.JTextField();
        inputJadwalCuci = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        btnDaftar = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoClean JavaDesk");
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));

        jPanel1.setBackground(new java.awt.Color(221, 241, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(776, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AutoClean-Assets/image.jpg")));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 262, 590));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HALAMAN");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PESAN UNTUK CUCI");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel4.setText("Flavar");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 527, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipe Kendaraan");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 155, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Merk Kendaraan");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 155, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nomor Telepon");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 232, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Plat Kendaraan");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 232, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tipe...", "Roda dua", "Roda Empat" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 177, 132, -1));
        jPanel1.add(inputNomorTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 254, 195, -1));
        jPanel1.add(inputMerkKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 177, 269, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Opsi Pencucian");
        jLabel10.setToolTipText("");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 308, -1, -1));

        inputOpsiPencucian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Opsi...", "Level 1 (Low Service) - Rp. 20.000", "Level 2 (Mid Service) - Rp. 50.000", "Level 3 (Full Service) - Rp. 100.000" }));
        inputOpsiPencucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOpsiPencucianActionPerformed(evt);
            }
        });
        jPanel1.add(inputOpsiPencucian, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 330, 195, -1));
        jPanel1.add(inputPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 254, 218, -1));
        jPanel1.add(inputJadwalCuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 411, 455, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jadwal Cuci");
        jLabel11.setToolTipText("");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 389, -1, -1));

        btnDaftar.setText("KIRIM");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 467, 203, -1));

        historyButton.setText("RIWAYAT");
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(historyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 531, 167, -1));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AutoClean-Assets/logout.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 40, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AutoClean-Assets/background.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 800, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Menangani aksi ketika tombol "KELUAR" diklik.
     * Menampilkan pesan logout dan kembali ke halaman login.
     * 
     * @param evt event aksi tombol keluar
     */
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Logout berhasil!");
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * Menangani aksi ketika tombol "RIWAYAT" diklik.
     * Membuka jendela untuk melihat riwayat booking berdasarkan username yang login.
     * 
     * @param evt event aksi tombol riwayat
     */
    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        new ViewBooking_Pelanggan(Login.loggedInUsername).setVisible(true);
        dispose();
    }//GEN-LAST:event_historyButtonActionPerformed

    /**
     * Menangani aksi ketika tombol "KIRIM" diklik.
     * Validasi input, instansiasi objek PelangganModel, 
     * serta menyimpan data ke database.
     * 
     * @param evt event aksi tombol daftar
      */
    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        String username = Login.loggedInUsername;
        String telp = inputNomorTelp.getText();
        String tipe = jComboBox1.getSelectedItem().toString();
        String plat = inputPlat.getText();
        String merk = inputMerkKendaraan.getText();

        if (tipe.equals("Pilih Tipe...")) {
            JOptionPane.showMessageDialog(this, "Silakan pilih tipe kendaraan yang valid!");
            return;
        }
        String opsi = inputOpsiPencucian.getSelectedItem().toString();

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String jadwal = sdf.format(inputJadwalCuci.getDate());

        User user = new PelangganModel(username, telp, tipe, merk, plat, opsi, jadwal) {
            @Override
            public void login() {
                JOptionPane.showMessageDialog(null, "Berhasil Pesan");
            }

            @Override
            public void logout() {
                JOptionPane.showMessageDialog(null, "Salah");
            }
        };
        simpanKeDatabase(user); // kamu bisa implementasi simpan sesuai field ini

        if (user instanceof PelangganModel pelangganModel) {
            pelangganModel.tampilkanInfo();
            pelangganModel.login();
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void inputOpsiPencucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOpsiPencucianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOpsiPencucianActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    
    
        
    /**
     * Menyimpan data pelanggan ke database jika objek user merupakan instance dari PelangganModel.
     * Menyimpan data seperti username, no telepon, tipe dan merk kendaraan, plat, opsi cuci, dan jadwal cuci.
     * 
     * @param user Objek user bertipe User yang telah di-cast menjadi PelangganModel
     */
    private void simpanKeDatabase(User user) {
    try {
        if (user instanceof PelangganModel p) {

            String sql = "INSERT INTO pelanggan (username, no_telp, tipe_kendaraan, merk_kendaraan, plat_kendaraan, opsi_pencucian, jadwal_cuci) " +
                         "VALUES (?, ?, ?, ?, ?, ?, ?)";

            java.sql.Connection conn = AutoClean_Connection.Koneksi.connect();
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, p.getUsername());
            stmt.setString(2, p.getNomorTelepon());
            stmt.setString(3, p.getTipeKendaraan());
            stmt.setString(4, p.getMerkKendaraan());
            stmt.setString(5, p.getPlatNomor());
            stmt.setString(6, p.getOpsiCuci());
            stmt.setString(7, p.getJadwalCuci());

            stmt.executeUpdate();
        }
    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pelanggan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton historyButton;
    private com.toedter.calendar.JDateChooser inputJadwalCuci;
    private javax.swing.JTextField inputMerkKendaraan;
    private javax.swing.JTextField inputNomorTelp;
    private javax.swing.JComboBox<String> inputOpsiPencucian;
    private javax.swing.JTextField inputPlat;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
