/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Autoclean_Form;

/**
 *
 * @author MyBook Hype AMD
 */


import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.Random;
import javax.swing.*;


public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        ImageIcon img = new ImageIcon("AutoClean-Assets/logo.png");
        setIconImage(img.getImage());
        setResizable(false);
        setLocationRelativeTo(null);
        generateCaptcha();
    }
    
    String generatedCaptcha = "";


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JTextField();
        RegisterUsername = new javax.swing.JTextField();
        ConfirmUsername = new javax.swing.JTextField();
        registerPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblCaptcha = new javax.swing.JLabel();
        txtCaptchaInput = new javax.swing.JTextField();
        btnRefreshCaptcha = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        toLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 241, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(776, 520));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 240, 90, 21);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Pesan Janji Temu Mobil Pesan Janji Temu Mobil");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 70, 420, 25);

        jLabel4.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 36)); // NOI18N
        jLabel4.setText("Register AutoClean JavaDesk");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 40, 430, 40);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Confirm Username");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 180, 160, 24);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Username");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 120, 90, 24);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Input Captcha");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 340, 160, 21);

        confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(confirmPassword);
        confirmPassword.setBounds(220, 300, 260, 30);
        jPanel1.add(RegisterUsername);
        RegisterUsername.setBounds(220, 120, 260, 30);

        ConfirmUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmUsername);
        ConfirmUsername.setBounds(220, 180, 260, 30);

        registerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(registerPassword);
        registerPassword.setBounds(220, 240, 260, 30);

        btnRegister.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.setBorder(null);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(60, 480, 170, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AutoClean-Assets/logo.png")));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 170, 200, 200);

        lblCaptcha.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblCaptcha.setText("rand");
        jPanel1.add(lblCaptcha);
        lblCaptcha.setBounds(70, 380, 70, 24);

        txtCaptchaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaptchaInputActionPerformed(evt);
            }
        });
        jPanel1.add(txtCaptchaInput);
        txtCaptchaInput.setBounds(220, 370, 260, 50);

        btnRefreshCaptcha.setText("Refresh code");
        btnRefreshCaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCaptchaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefreshCaptcha);
        btnRefreshCaptcha.setBounds(60, 440, 120, 23);

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setText("Confirm Password");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 300, 160, 21);

        toLogin.setBackground(new java.awt.Color(221, 241, 255));
        toLogin.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        toLogin.setForeground(new java.awt.Color(153, 153, 255));
        toLogin.setText("Sudah Punya akun?, Login saja");
        toLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        toLogin.setBorderPainted(false);
        toLogin.setContentAreaFilled(false);
        toLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toLogin.setFocusPainted(false);
        toLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLoginActionPerformed(evt);
            }
        });
        jPanel1.add(toLogin);
        toLogin.setBounds(530, 510, 210, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordActionPerformed

    private void ConfirmUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmUsernameActionPerformed

    private void registerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPasswordActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    String inputCaptcha = txtCaptchaInput.getText();
    
    if (!inputCaptcha.equals(generatedCaptcha)) {
        JOptionPane.showMessageDialog(this, "Captcha salah!");
        generateCaptcha(); // regenerate
        return;
        
    }
        
    String username = RegisterUsername.getText();
    String confirmUsername = ConfirmUsername.getText();
    String password = registerPassword.getText();
    String confirmPass = confirmPassword.getText();

if (!username.equals(confirmUsername)) {
    JOptionPane.showMessageDialog(this, "Username tidak cocok!");
    return;
}
if (!password.equals(confirmPass)) {
    JOptionPane.showMessageDialog(this, "Password tidak cocok!");
    return;
}

try {
    // koneksi ke database
    Class.forName("com.mysql.cj.jdbc.Driver");
    java.sql.Connection conn = java.sql.DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/autoclean_javadesk", "root", ""); // sesuaikan password

    // cek apakah username sudah dipakai
    java.sql.PreparedStatement checkStmt = conn.prepareStatement("SELECT * FROM akun WHERE username=?");
    checkStmt.setString(1, username);
    java.sql.ResultSet rs = checkStmt.executeQuery();
    if (rs.next()) {
        JOptionPane.showMessageDialog(this, "Username sudah digunakan!");
        return;
    }

    // insert data
    java.sql.PreparedStatement pst = conn.prepareStatement("INSERT INTO akun (username, password) VALUES (?, ?)");
    pst.setString(1, username);
    pst.setString(2, password);
    pst.executeUpdate();
    
    JOptionPane.showMessageDialog(this, "Registrasi berhasil!");
    new Login().setVisible(true);
    dispose();
    
    // kosongkan form
    RegisterUsername.setText("");
    ConfirmUsername.setText("");
    registerPassword.setText("");
    confirmPassword.setText("");
    txtCaptchaInput.setText("");
    generateCaptcha();

    conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    
        
        
        
    }    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtCaptchaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaptchaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaptchaInputActionPerformed

    private void btnRefreshCaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCaptchaActionPerformed
    generateCaptcha();
    }//GEN-LAST:event_btnRefreshCaptchaActionPerformed

    private void toLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLoginActionPerformed
       new Login().setVisible(true);
       dispose();
    }//GEN-LAST:event_toLoginActionPerformed

    private void generateCaptcha() {
    String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    StringBuilder captcha = new StringBuilder();
    Random rand = new Random();
    for (int i = 0; i < 4; i++) {
        captcha.append(chars.charAt(rand.nextInt(chars.length())));
    }
    generatedCaptcha = captcha.toString();
    lblCaptcha.setText(generatedCaptcha); // Tampilkan captcha ke label
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfirmUsername;
    private javax.swing.JTextField RegisterUsername;
    private javax.swing.JButton btnRefreshCaptcha;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField confirmPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCaptcha;
    private javax.swing.JTextField registerPassword;
    private javax.swing.JButton toLogin;
    private javax.swing.JTextField txtCaptchaInput;
    // End of variables declaration//GEN-END:variables
}
