/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Autoclean_Form;

/**
 * Kelas ViewBooking_Pelanggan menampilkan daftar riwayat pemesanan pelanggan.
 * Kelas ini memuat data dari tabel `pelanggan` di database berdasarkan username yang sedang login.
 * Fitur utama:
 * - Menampilkan data pemesanan pelanggan
 * - Bayar pesanan (membuka form BayarPesanan)
 * - Batalkan pesanan (update status menjadi "Dibatalkan")
 * - Hapus pesanan
 * - Refresh tabel
 * - Kembali ke halaman pelanggan
 *
 * @author Fadhil
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


public class ViewBooking_Pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form ViewBooking_Pelanggan
     */
    
    private String usernameLogin;
    
    /**
 * Konstruktor ViewBooking_Pelanggan.
 * Inisialisasi GUI dan memuat data riwayat pemesanan berdasarkan username login.
 *
 * @param usernameLogin username pelanggan yang sedang login
 */
    public ViewBooking_Pelanggan(String usernameLogin) {
        this.usernameLogin = usernameLogin;
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        tampilDataHistory();  
        setTitle("AutClean JavaDesk");
        tabelHistory.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }
    
    /**
 * Method untuk mengambil dan menampilkan data pemesanan pelanggan dari database
 * ke dalam tabel berdasarkan username yang sedang login.
 */
    private void tampilDataHistory() {
        
        try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/autoclean_javadesk", "root", "");
        Statement stmt = conn.createStatement();
        
        // FILTER berdasarkan usernameLogin
        String sql = "SELECT * FROM pelanggan WHERE username = '" + usernameLogin + "'";
        
        ResultSet rs = stmt.executeQuery(sql);

        DefaultTableModel model = (DefaultTableModel) tabelHistory.getModel();
        model.setRowCount(0); // bersihin tabel dulu

        int no = 1;
        while (rs.next()) {
            Object[] row = {
                no++,
                rs.getString("no_telp"),
                rs.getString("tipe_kendaraan"),
                rs.getString("merk_kendaraan"),
                rs.getString("plat_kendaraan"),
                rs.getString("opsi_pencucian"),
                rs.getString("jadwal_cuci"),
                rs.getString("status")
            };
            model.addRow(row);
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error : " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHistory = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 241, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("RIYAWAT PEMESANAN");

        tabelHistory.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Telp", "Tipe Kendaraan", "Merk Kendaraan", "Plat Kendaraan", "Opsi Pencucian", "Jadwal Cuci", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelHistory.getTableHeader().setReorderingAllowed(false);
        tabelHistory.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelHistoryAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelHistory);
        if (tabelHistory.getColumnModel().getColumnCount() > 0) {
            tabelHistory.getColumnModel().getColumn(0).setResizable(false);
            tabelHistory.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelHistory.getColumnModel().getColumn(1).setResizable(false);
            tabelHistory.getColumnModel().getColumn(2).setResizable(false);
            tabelHistory.getColumnModel().getColumn(3).setResizable(false);
            tabelHistory.getColumnModel().getColumn(4).setResizable(false);
            tabelHistory.getColumnModel().getColumn(5).setResizable(false);
            tabelHistory.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabelHistory.getColumnModel().getColumn(6).setResizable(false);
            tabelHistory.getColumnModel().getColumn(7).setResizable(false);
        }

        backBtn.setText("KEMBALI");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnBatal.setText("Batalkan");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        refreshBtn.setText("Muat Ulang");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBayar)
                    .addComponent(btnBatal)
                    .addComponent(refreshBtn)
                    .addComponent(btnHapus))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
 * Digunakan saat tabel ditambahkan ke container, akan menampilkan ulang data history.
 *
 * @param evt event dari tabel ditambahkan ke panel
 */
    private void tabelHistoryAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelHistoryAncestorAdded
        // TODO add your handling code here:
                try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/autoclean_javadesk", "root", "");
            Statement stmt = conn.createStatement();

            String sql = "SELECT * FROM pelanggan WHERE username = '" + usernameLogin + "'";

            ResultSet rs = stmt.executeQuery(sql);

            DefaultTableModel model = (DefaultTableModel) tabelHistory.getModel();
            model.setRowCount(0);

            int no = 1;
            while (rs.next()) {
                Object[] row = {
                    no++,
                    rs.getString("no_telp"),
                    rs.getString("tipe_kendaraan"),
                    rs.getString("merk_kendaraan"),
                    rs.getString("plat_kendaraan"),
                    rs.getString("opsi_pencucian"),
                    rs.getString("jadwal_cuci"),
                    rs.getString("status")
                };
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            System.out.println("Error : " + e.getMessage());
        }
        
        
    }//GEN-LAST:event_tabelHistoryAncestorAdded

    
    /**
 * Event handler untuk tombol "Kembali".
 * Akan kembali ke halaman utama pelanggan.
 *
 * @param evt event klik tombol
 */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new Pelanggan().setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
 * Event handler untuk tombol "Bayar".
 * Membuka form pembayaran jika pesanan belum dibayar.
 *
 * @param evt event klik tombol
 */
    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
    int selectedRow = tabelHistory.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih salah satu pesanan dulu.");
        return;
    }

    String platKendaraan = tabelHistory.getValueAt(selectedRow, 4).toString();
    String jadwalCuci = tabelHistory.getValueAt(selectedRow, 6).toString();
    String status = tabelHistory.getValueAt(selectedRow, 7).toString();

    // Pesanan yang tidak bisa dibayar:
    if ("Sedang Dicuci".equalsIgnoreCase(status) || 
        "Dibatalkan".equalsIgnoreCase(status) || 
        "Selesai".equalsIgnoreCase(status)) 
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Pesanan tidak bisa dibayar (Status: " + status + ").");
        return;
    }

    String opsiPencucian = tabelHistory.getValueAt(selectedRow, 5).toString();
    String hargaStr = opsiPencucian.substring(opsiPencucian.indexOf("Rp.") + 4).replace(".", "").replace(",", "");
    int harga = Integer.parseInt(hargaStr);

    BayarPesanan bayarForm = new BayarPesanan(usernameLogin, harga, platKendaraan, jadwalCuci);
    bayarForm.setVisible(true);
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
 * Event handler untuk tombol "Muat Ulang".
 * Mengambil ulang data riwayat pemesanan dari database dan menampilkannya ke tabel.
 *
 * @param evt event klik tombol
 */
    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        tampilDataHistory();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
 * Event handler untuk tombol "Batalkan".
 * Mengubah status pesanan menjadi "Dibatalkan" jika belum dalam proses pencucian.
 *
 * @param evt event klik tombol
 */
    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    int selectedRow = tabelHistory.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih salah satu pesanan dulu.");
        return;
    }

    String platKendaraan = tabelHistory.getValueAt(selectedRow, 4).toString();
    String jadwalCuci = tabelHistory.getValueAt(selectedRow, 6).toString();
    String status = tabelHistory.getValueAt(selectedRow, 7).toString();

    // Pesanan yang tidak bisa dibatalkan:
    if ("Sedang Dicuci".equalsIgnoreCase(status) || 
        "Dibatalkan".equalsIgnoreCase(status) || 
        "Selesai".equalsIgnoreCase(status)) 
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Pesanan tidak bisa dibatalkan (Status: " + status + ").");
        return;
    }

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/autoclean_javadesk", "root", "");
        Statement stmt = conn.createStatement();

        String updateSql = "UPDATE pelanggan SET status = 'Dibatalkan' WHERE username = '" + usernameLogin + "' AND plat_kendaraan = '" + platKendaraan + "' AND jadwal_cuci = '" + jadwalCuci + "'";
        stmt.executeUpdate(updateSql);

        stmt.close();
        conn.close();

        tampilDataHistory();

        javax.swing.JOptionPane.showMessageDialog(this, "Pesanan berhasil dibatalkan.");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
 * Event handler untuk tombol "Hapus".
 * Menghapus data pemesanan dari database jika belum dalam proses pencucian.
 *
 * @param evt event klik tombol
 */
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
            int selectedRow = tabelHistory.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih salah satu pesanan dulu.");
        return;
    }

    String platKendaraan = tabelHistory.getValueAt(selectedRow, 4).toString();
    String jadwalCuci = tabelHistory.getValueAt(selectedRow, 6).toString();
    String status = tabelHistory.getValueAt(selectedRow, 7).toString();

    if ("Sedang Dicuci".equalsIgnoreCase(status)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pesanan sedang dicuci, tidak bisa dihapus.");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus pesanan ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/autoclean_javadesk", "root", "");
            Statement stmt = conn.createStatement();

            String deleteSql = "DELETE FROM pelanggan WHERE username = '" + usernameLogin + "' AND plat_kendaraan = '" + platKendaraan + "' AND jadwal_cuci = '" + jadwalCuci + "'";
            stmt.executeUpdate(deleteSql);

            stmt.close();
            conn.close();

            tampilDataHistory();

            javax.swing.JOptionPane.showMessageDialog(this, "Pesanan berhasil dihapus.");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi error: " + e.getMessage());
        }
    }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBooking_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBooking_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBooking_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBooking_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new ViewBooking_Pelanggan(Login.loggedInUsername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable tabelHistory;
    // End of variables declaration//GEN-END:variables
}
