/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Autoclean_Form;

/**
 *
 * @author Fadhil
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

public class ViewBooking_Pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form ViewBooking_Pelanggan
     */
    
    private String usernameLogin;
    
    public ViewBooking_Pelanggan() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        tampilDataHistory();    
        tabelHistory.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }
    
    private void tampilDataHistory() {
        
        try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/autoclean_javadesk", "root", "");
        Statement stmt = conn.createStatement();
        
        // FILTER berdasarkan usernameLogin
        String sql = "SELECT * FROM pelanggan WHERE username = '" + usernameLogin + "'";
        
        ResultSet rs = stmt.executeQuery(sql);

        DefaultTableModel model = (DefaultTableModel) tabelHistory.getModel();
        model.setRowCount(0); // bersihin tabel dulu

        int no = 1;
        while (rs.next()) {
            Object[] row = {
                no++,
                rs.getString("no_telp"),
                rs.getString("tipe_kendaraan"),
                rs.getString("merk_kendaraan"),
                rs.getString("plat_kendaraan"),
                rs.getString("opsi_pencucian"),
                rs.getString("jadwal_cuci"),
                rs.getString("status")
            };
            model.addRow(row);
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error : " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHistory = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 241, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("RIYAWAT PEMESANAN");

        tabelHistory.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Telp", "Tipe Kendaraan", "Merk Kendaraan", "Plat Kendaraan", "Opsi Pencucian", "Jadwal Cuci", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelHistory.getTableHeader().setReorderingAllowed(false);
        tabelHistory.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelHistoryAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelHistory);
        if (tabelHistory.getColumnModel().getColumnCount() > 0) {
            tabelHistory.getColumnModel().getColumn(0).setResizable(false);
            tabelHistory.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabelHistory.getColumnModel().getColumn(1).setResizable(false);
            tabelHistory.getColumnModel().getColumn(2).setResizable(false);
            tabelHistory.getColumnModel().getColumn(3).setResizable(false);
            tabelHistory.getColumnModel().getColumn(4).setResizable(false);
            tabelHistory.getColumnModel().getColumn(5).setResizable(false);
            tabelHistory.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabelHistory.getColumnModel().getColumn(6).setResizable(false);
            tabelHistory.getColumnModel().getColumn(7).setResizable(false);
        }

        backBtn.setText("KEMBALI");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnBatal.setText("Batalkan");

        refreshBtn.setText("Muat Ulang");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBayar)
                    .addComponent(btnBatal)
                    .addComponent(refreshBtn))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelHistoryAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelHistoryAncestorAdded
        // TODO add your handling code here:
        
        try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/autoclean_javadesk", "root", "");
        Statement stmt = conn.createStatement();

        // Ambil username yg login
        String currentUser = Login.loggedInUsername;

        // FILTER berdasarkan username yg login
        String sql = "SELECT * FROM pelanggan WHERE username = '" + currentUser + "'";

        ResultSet rs = stmt.executeQuery(sql);

        DefaultTableModel model = (DefaultTableModel) tabelHistory.getModel();
        model.setRowCount(0); // bersihin tabel dulu

        int no = 1;
        while (rs.next()) {
            Object[] row = {
                no++,
                rs.getString("no_telp"),
                rs.getString("tipe_kendaraan"),
                rs.getString("merk_kendaraan"),
                rs.getString("plat_kendaraan"),
                rs.getString("opsi_pencucian"),
                rs.getString("jadwal_cuci"),
                rs.getString("status")
            };
            model.addRow(row);
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error : " + e.getMessage());
    }
        
    }//GEN-LAST:event_tabelHistoryAncestorAdded

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new Pelanggan().setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        
    int[] selectedRows = tabelHistory.getSelectedRows();

    if (selectedRows.length == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu pesanan yang mau dibayar.");
        return;
    }

    int totalHarga = 0;

    for (int row : selectedRows) {
    String opsiPencucian = tabelHistory.getValueAt(row, 5).toString();

    System.out.println("DEBUG opsiPencucian: " + opsiPencucian); 

    try {
        String[] parts = opsiPencucian.split("-");
        String hargaStr = parts[parts.length - 1].replaceAll("[^\\d]", "");
        System.out.println("DEBUG hargaStr: " + hargaStr);
        int harga = Integer.parseInt(hargaStr);
        totalHarga += harga;
    } catch (Exception e) {
        System.out.println("Gagal parsing harga di row " + row + ": " + e.getMessage());
    }
}

        int row = tabelHistory.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu pesanan yang mau dibayar.");
            return;
        }

        String platKendaraan = tabelHistory.getValueAt(row, 4).toString();
        String jadwalCuci = tabelHistory.getValueAt(row, 6).toString();

        BayarPesanan bayarForm = new BayarPesanan(Login.loggedInUsername, totalHarga, platKendaraan, jadwalCuci);
        bayarForm.setVisible(true);

    }//GEN-LAST:event_btnBayarActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        tampilDataHistory();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBooking_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBooking_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBooking_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBooking_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBooking_Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable tabelHistory;
    // End of variables declaration//GEN-END:variables
}
